### PR TITLE
Add state option to login query string

### PR DESCRIPTION
**Pull request by dwilt**
hey @andyrichardson I want to leverage the [`state` parameter](https://workos.com/docs/reference/sso/authorize/get#authorize-state) so I added the variable to the login `req.query` and am passing it into `getAuthorizationURL`. Let me know if this looks ok

### CODE REVIEW

**Comment by andyrichardson** [comment]
Hey dwilt, does the following work for your use case?

```js
app.use("/workos/authenticate", (req, res, next) => {
  const state = { redirect: req.query.redirect, timeOfInvocation: Date.now() };
  return passport.authenticate("workos", { state: btoa(JSON.stringify(state)) })
})
```

This should work similar to other OAuth strategies (github, gitlab, etc)

**Comment by dwilt** [comment]
@andyrichardson unfortunately, I don't think so. I'm using `NextJS` and don't have access to the `req` object when I call `passport.authenticate`. Here is my class which instantiaties a new `PassportStrategy` with `workos`:

```ts
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { PassportStrategy } from '@nestjs/passport';
import { WorkOSSSOStrategy as Strategy } from 'passport-workos';

@Injectable()
export class WorkOSSSOStrategy extends PassportStrategy(Strategy, 'workos') {
  constructor(configService: ConfigService) {
    super(
      {
        clientID: configService.get('WORKOS_CLIENT_ID'),
        clientSecret: configService.get('WORKOS_API_KEY'),
        callbackURL: 'http://localhost:4001/api/v1/auth/workos/callback',
      },
      // TODO: get typings put in so this can be properly typed
      (_req, _accessToken, _refreshToken, profile, done) => {
        return done(undefined, profile);
      },
    );
  }
}
```

**Comment by andyrichardson** [comment]
Thanks for clarifying, I see what you mean.

It looks like you might need to go the inheritance route in this case ([example here](https://stackoverflow.com/questions/60857548/how-to-pass-state-during-nest-js-authentication-flow)).

**Comment by dwilt** [comment]
Yea, I think this will work. Thanks for calling out.

**Comment by dwilt** [comment]
@andyrichardson yep this worked! Thanks!!!

**Pull request closed without merging**
